namespace LinKit.Core.Grpc;

/// <summary>
/// Marks a CQRS Command or Query to be exposed as a gRPC service method.
/// The source generator will create a gRPC service implementation that maps
/// the gRPC request to this CQRS request, calls the mediator, and maps the result back.
/// </summary>
[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
public sealed class GrpcEndpointAttribute : Attribute
{
    /// <summary>
    /// The base type of the gRPC service, generated by Grpc.Tools.
    /// E.g., typeof(UserService.UserServiceBase)
    /// </summary>
    public Type ServiceBaseType { get; }

    /// <summary>
    /// The name of the RPC method in the .proto file that this request corresponds to.
    /// E.g., "GetUser"
    /// </summary>
    public string MethodName { get; }

    public GrpcEndpointAttribute(Type serviceBaseType, string methodName)
    {
        ServiceBaseType = serviceBaseType;
        MethodName = methodName;
    }
}
