using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace LinKit.Generator.Generators;

internal record BackgroundJobInfo(
    string JobName,
    string FullTypeName,
    bool? IsCommand,
    string AssemblyName
);

internal static class BackgroundJobGeneratorPart
{
    private const string BackgroundJobAttributeName =
        "LinKit.Core.BackgroundJobs.BackgroundJobAttribute";
    private const string ICommandInterfaceName = "LinKit.Core.Cqrs.ICommand";
    private const string IQueryInterfaceName = "LinKit.Core.Cqrs.IQuery";

    public static void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<BackgroundJobInfo?> jobDeclarations = context
            .SyntaxProvider.ForAttributeWithMetadataName(
                BackgroundJobAttributeName,
                predicate: (node, _) => node is ClassDeclarationSyntax or RecordDeclarationSyntax,
                transform: (ctx, _) => GetBackgroundJobInfo(ctx)
            )
            .Where(info => info is not null && info.IsCommand is not null);

        context.RegisterSourceOutput(
            jobDeclarations.Collect(),
            (spc, jobs) =>
            {
                List<BackgroundJobInfo> validJobs = jobs.OfType<BackgroundJobInfo>().ToList();
                if (!validJobs.Any())
                {
                    return;
                }

                string source = GenerateJobTypeMapper(validJobs);
                spc.AddSource(
                    "BackgroundJobTypeMapper.g.cs",
                    SourceText.From(source, Encoding.UTF8)
                );
                spc.AddSource(
                    "BackgroundJobExtensions.g.cs",
                    SourceText.From(GenerateBuilderExtension(validJobs), Encoding.UTF8)
                );
            }
        );
    }

    private static BackgroundJobInfo? GetBackgroundJobInfo(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol classSymbol)
        {
            return null;
        }

        AttributeData attributeData = context.Attributes[0];
        if (
            attributeData.ConstructorArguments.Length == 0
            || attributeData.ConstructorArguments[0].Value is not string jobName
            || string.IsNullOrEmpty(jobName)
        )
        {
            return null;
        }

        bool? isCommand = null;
        foreach (INamedTypeSymbol iface in classSymbol.AllInterfaces)
        {
            string originalDefinition = iface.OriginalDefinition.ToDisplayString();
            if (originalDefinition.StartsWith(IQueryInterfaceName))
            {
                isCommand = false;
                break;
            }
            if (originalDefinition.StartsWith(ICommandInterfaceName))
            {
                isCommand = true;
            }
        }

        if (isCommand is null)
        {
            return null;
        }

        string fullTypeName = classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string assemblyName = classSymbol.ContainingAssembly.Name;
        return new BackgroundJobInfo(jobName, fullTypeName, isCommand, assemblyName);
    }

    private static string GenerateJobTypeMapper(IReadOnlyList<BackgroundJobInfo> jobs)
    {
        StringBuilder sb = new StringBuilder();
        sb.AppendLine("// <auto-generated> by LinKit.Generator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine("namespace LinKit.Core.BackgroundJobs");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine(
            "    /// Provides a mapping from a job name to its corresponding Type, CQRS type, and a new instance."
        );
        sb.AppendLine("    /// This class is auto-generated and should not be modified manually.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public class BackgroundJobMapper : IBackgroundJobMapper");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine(
            "        /// Gets information about a background job from its configured name."
        );
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <param name=\"jobName\">The unique name of the job.</param>");
        sb.AppendLine(
            "        /// <returns>An instance of BackgroundJobInfo containing the job's details.</returns>"
        );
        sb.AppendLine("        public JobInfo GetJobInfoByName(string jobName)");
        sb.AppendLine("        {");
        sb.AppendLine("            return jobName switch");
        sb.AppendLine("            {");

        foreach (BackgroundJobInfo? job in jobs.OrderBy(j => j.JobName))
        {
            sb.AppendLine(
                $@"                ""{job.JobName}"" => new JobInfo(typeof({job.FullTypeName}), {job.IsCommand.ToString().ToLower()}, new {job.FullTypeName}()),"
            );
        }

        sb.AppendLine(
            @"                _ => throw new ArgumentOutOfRangeException(nameof(jobName), $""Background job '{jobName}' is not registered."")"
        );
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GenerateBuilderExtension(IReadOnlyList<BackgroundJobInfo> jobs)
    {
        string namespaceName = jobs[0].AssemblyName;
        return $@"using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Options;
using LinKit.Core.BackgroundJobs;
using System.Linq;

namespace {namespaceName}
{{
    public static class BackgroundJobExtensions
    {{
        /// <summary>
        /// Adds BackgroundJobManager with auto-generated mapper (1 LINE ONLY!)
        /// </summary>
        public static WebApplicationBuilder AddBackgroundJobs(
            this WebApplicationBuilder builder,
            string jsonFile = ""BackgroundJobsConfig.json"")
        {{
            // 1. JSON + RELOAD = TRUE
            builder.Configuration.AddJsonFile(jsonFile, optional: false, reloadOnChange: true);

            // 2. CONFIG
            builder.Services.Configure<BackgroundJobConfig>(
                builder.Configuration.GetSection(""BackgroundJobConfig""));

            // 3. MAPPER (AUTO-GENERATED)
            if (!builder.Services.Any(d =>
                d.ServiceType == typeof(IBackgroundJobMapper)))
            {{
                builder.Services.AddSingleton<IBackgroundJobMapper, BackgroundJobMapper>();
            }}

            // 4. HOSTED SERVICE (CHECK DUPLICATE)
            if (!builder.Services.Any(d =>
                d.ImplementationType == typeof(BackgroundJobManager)))
            {{
                builder.Services.AddHostedService<BackgroundJobManager>();
            }}

            return builder;
        }}
    }}
}}";
    }
}
