using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace LinKit.Generator.Generators;

internal record BackgroundJobInfo(
    string JobName,
    string FullTypeName,
    string NamespaceOfType,
    bool? IsCommand,
    string AssemblyName
);

internal static class BackgroundJobGeneratorPart
{
    private const string BackgroundJobAttributeName =
        "LinKit.Core.BackgroundJobs.BackgroundJobAttribute";
    private const string ICommandInterfaceName = "LinKit.Core.Cqrs.ICommand";
    private const string IQueryInterfaceName = "LinKit.Core.Cqrs.IQuery";

    public static void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<BackgroundJobInfo?> jobDeclarations = context
            .SyntaxProvider.ForAttributeWithMetadataName(
                BackgroundJobAttributeName,
                predicate: (node, _) => node is ClassDeclarationSyntax or RecordDeclarationSyntax,
                transform: (ctx, _) => GetBackgroundJobInfo(ctx)
            )
            .Where(info => info is not null && info.IsCommand is not null);

        context.RegisterSourceOutput(
            jobDeclarations.Collect(),
            (spc, jobs) =>
            {
                List<BackgroundJobInfo> validJobs = jobs.OfType<BackgroundJobInfo>().ToList();
                if (!validJobs.Any())
                {
                    return;
                }

                string source = GenerateJobTypeMapper(validJobs);
                spc.AddSource(
                    "BackgroundJobTypeMapper.g.cs",
                    SourceText.From(source, Encoding.UTF8)
                );
                spc.AddSource(
                    "BackgroundJobExtensions.g.cs",
                    SourceText.From(GenerateBuilderExtension(validJobs), Encoding.UTF8)
                );
                var assemblyName = validJobs[0].AssemblyName;
                spc.AddSource(
                    "BackgroundJobGlobalUsing.g.cs",
                    SourceText.From(
                        GlobalUsingGenerator.GenGlobalUsing(new List<string> { assemblyName }),
                        Encoding.UTF8
                    )
                );
            }
        );
    }

    private static BackgroundJobInfo? GetBackgroundJobInfo(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol classSymbol)
        {
            return null;
        }

        AttributeData attributeData = context.Attributes[0];
        if (
            attributeData.ConstructorArguments.Length == 0
            || attributeData.ConstructorArguments[0].Value is not string jobName
            || string.IsNullOrEmpty(jobName)
        )
        {
            return null;
        }

        bool? isCommand = null;
        foreach (INamedTypeSymbol iface in classSymbol.AllInterfaces)
        {
            string originalDefinition = iface.OriginalDefinition.ToDisplayString();
            if (originalDefinition.StartsWith(IQueryInterfaceName))
            {
                isCommand = false;
                break;
            }
            if (originalDefinition.StartsWith(ICommandInterfaceName))
            {
                isCommand = true;
            }
        }

        if (isCommand is null)
        {
            return null;
        }

        string fullTypeName = classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string @namespace = classSymbol.ContainingNamespace?.ToDisplayString() ?? string.Empty;
        string assemblyName = classSymbol.ContainingAssembly.Name;

        return new BackgroundJobInfo(jobName, fullTypeName, @namespace, isCommand, assemblyName);
    }

    private static string GenerateJobTypeMapper(IReadOnlyList<BackgroundJobInfo> jobs)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated> by LinKit.Generator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using LinKit.Core.Cqrs;");
        sb.AppendLine();
        sb.AppendLine("namespace LinKit.Core.BackgroundJobs");
        sb.AppendLine("{");
        sb.AppendLine("    internal class BackgroundJobMapper : IBackgroundJobMapper");
        sb.AppendLine("    {");
        sb.AppendLine("        public JobInfo GetJobInfoByName(string jobName)");
        sb.AppendLine("        {");
        sb.AppendLine("            return jobName switch");
        sb.AppendLine("            {");

        foreach (var job in jobs.OrderBy(j => j.JobName))
        {
            var executorCall =
                job.IsCommand == true
                    ? $"mediator.SendAsync(({job.FullTypeName})instance, token)"
                    : $"mediator.QueryAsync(({job.FullTypeName})instance, token)";

            sb.AppendLine(
                $$"""
                            "{{job.JobName}}" => new JobInfo(
                                typeof({{job.FullTypeName}}),
                                {{job.IsCommand.ToString().ToLower()}},
                                new {{job.FullTypeName}}(),
                                static async (mediator, instance, token) => await {{executorCall}}
                            ),
                """
            );
        }

        sb.AppendLine(
            @"                _ => throw new ArgumentOutOfRangeException(nameof(jobName), $""Background job '{jobName}' is not registered."")"
        );
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine(
            "        public Func<IMediator, CancellationToken, Task>? GetExecutor(string jobName, string embeddedData)"
        );
        sb.AppendLine("        {");
        sb.AppendLine("            return jobName switch");
        sb.AppendLine("            {");

        foreach (var job in jobs.OrderBy(j => j.JobName))
        {
            var executorCall =
                job.IsCommand == true
                    ? $"mediator.SendAsync(new {job.FullTypeName}(){{ EmbeddedData = embeddedData }}, token)"
                    : $"mediator.QueryAsync(new {job.FullTypeName}(){{ EmbeddedData = embeddedData }}, token)";

            sb.AppendLine(
                $$"""
                            "{{job.JobName}}" => async (mediator, token) => await {{executorCall}},
                """
            );
        }

        sb.AppendLine(
            @"                _ => throw new ArgumentOutOfRangeException(nameof(jobName), $""Background job '{jobName}' is not registered."")"
        );
        sb.AppendLine("            };");
        sb.AppendLine("        }");

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GenerateBuilderExtension(IReadOnlyList<BackgroundJobInfo> jobs)
    {
        string namespaceName = jobs[0].AssemblyName;
        var assemblyName = jobs[0].AssemblyName;
        return $@"// <auto-generated> by LinKit.Generator
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Options;
using LinKit.Core.BackgroundJobs;
using System.Linq;
using System.IO;
using System;
using LinKit.Core;

namespace {namespaceName}
{{
    internal static class BackgroundJobExtensions
    {{
        public static WebApplicationBuilder AddBackgroundJobs(
            this WebApplicationBuilder builder,
            string jsonFile = ""BackgroundJobsConfig.json"")
        {{
            builder.Configuration.AddJsonFile(jsonFile, optional: true, reloadOnChange: true);

            var configSection = builder.Configuration.GetSection(""BackgroundJobConfig"");
            if (configSection.Exists())
            {{
                builder.Services.Configure<BackgroundJobConfig>(configSection);
            }}
            else
            {{
                Console.WriteLine($""[Warning] BackgroundJobConfig section not found in '{{jsonFile}}'. Using default configuration."");
                builder.Services.Configure<BackgroundJobConfig>(config => {{ }});
            }}

            string absoluteConfigPath = Path.GetFullPath(jsonFile);
            string directory = Path.GetDirectoryName(absoluteConfigPath) ?? Directory.GetCurrentDirectory();
            string historyFileName = Path.GetFileNameWithoutExtension(jsonFile) + ""_History.json"";
            string historyFilePath = Path.Combine(directory, historyFileName);

            builder.Services.TryAddSingleton<IJobHistoryLogger>(sp => new FileJobHistoryLogger(historyFilePath));

            builder.Services.AddKeyedSingleton<IBackgroundJobMapper, BackgroundJobMapper>(""{assemblyName}"");

            builder.Services.AddBackgroundJobManager();

            builder.Services.AddKeyedScoped<LinKit.Core.Cqrs.IMediator, LinKit.Generated.Cqrs.Mediator>(""{assemblyName}"");
            builder.Services.AddLinKitCqrs();

            return builder;
        }}
    }}
}}";
    }
}
