using System.Collections.Generic;
using System.Text;

namespace LinKit.Generator.Generators;

internal class GlobalUsingGenerator
{
    public static string GenGlobalUsing(List<string> namespaces)
    {
        var globalUsingsSource = new StringBuilder();
        globalUsingsSource.AppendLine("// <auto-generated/> by LinKit.Generator");
        globalUsingsSource.AppendLine();
        foreach (var ns in namespaces)
        {
            globalUsingsSource.AppendLine($"global using {ns};");
        }
        return globalUsingsSource.ToString();
    }
}
