namespace LinKit.Grpc;

/// <summary>
/// Marks a CQRS Command or Query to indicate that it should be dispatched
/// via a gRPC client call instead of an in-process handler.
/// </summary>
[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
public sealed class GrpcClientAttribute : Attribute
{
    /// <summary>
    /// The type of the gRPC client generated by Grpc.Tools.
    /// E.g., typeof(UserService.UserClient)
    /// </summary>
    public Type GrpcClientType { get; }

    /// <summary>
    /// The name of the RPC method to call on the gRPC client.
    /// E.g., "GetUserAsync"
    /// </summary>
    public string MethodName { get; }

    public GrpcClientAttribute(Type grpcClientType, string methodName)
    {
        GrpcClientType = grpcClientType;
        MethodName = methodName;
    }
}
