// <auto-generated> by LinKit.Generator
using System.Text.Json.Serialization;
using SampleWebApp.Features.Users;

namespace LinKit.Generated.Json
{
    [JsonSourceGenerationOptions(WriteIndented = false)]
    [JsonSerializable(typeof(CreateUserCommand))]
    internal partial class BackgroundJobJsonContext : JsonSerializerContext { }
}
